[package]
name = "woxel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmask = "0.5.0"
bitvec = "1.0.1"
glam = "0.24.1"
